all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    ci:
      hosts:
        ci_hosting:
          ansible_ssh_private_key_file: #TODO
          ansible_host: 84.201.134.115
          ansible_user: admin
