- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: "Prepare apt cache"
    ignore_errors: yes
    apt:
      autoremove: yes
      autoclean: yes
      update_cache: yes
      cache_valid_time: 86400

- hosts: ci_pipeline
  become: yes
  roles:
    - geerlingguy.docker

  tasks:
    - name: Copy docker-compose file
      become: yes
      copy:
        src: docker-compose.yml
        dest: /var

    - name: Shut down docker containers
      become: yes
      command: docker-compose --file /var/docker-compose.yml down --timeout 60
      register: shutdown_console

    - debug: msg="{{ shutdown_console.stdout }}"
    - debug: msg="{{ shutdown_console.stderr }}"

    - name: Build and start up docker containers
      become: yes
      command: docker-compose --file /var/docker-compose.yml up --detach
      register: startup_console

    - debug: msg="{{ startup_console.stdout }}"
    - debug: msg="{{ startup_console.stderr }}"
