all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    ci:
      hosts:
        ci_hosting:
          ansible_ssh_private_key_file: /Users/eugene/Dropbox/Eugene/Backups/agile-practices-dev.pem #TODO Set path to private key .pem file
          ansible_host: 84.201.134.115 #TODO Set CI hosting hostname
          ansible_user: admin #TODO Set CI host username for Ansible provisioning
