all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    ci:
      hosts:
        ci_hosting:
          ansible_ssh_private_key_file: #TODO Set path to private key .pem file
          ansible_host: #TODO Set CI hosting hostname
          ansible_user: #TODO Set CI host username for Ansible provisioning
