features:
  account: true
  client: true

---

server:
  port: 8080
  servlet:
    context-path: /dbo

spring:
  profiles:
    active: prod

---

spring:
  profiles: test
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

---

spring:
  profiles: it
  datasource:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:memory:dbo-db;create=true
    username: APP
    password: APP
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase: #https://javadeveloperzone.com/spring-boot/spring-boot-liquibase-example/
    enabled: true
    contexts: prod, qa
    change-log: classpath:/db-changelog.xml
    liquibaseSchema: liquibase
    user: APP
    password: APP

---

spring:
  profiles: qa
  datasource:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:dbo-db;create=true
    username: APP
    password: APP
    hikari:
      poolName: hikari-connection-pool
      maximumPoolSize: 2
      minimumIdle: 2
      idleTimeout: 600000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    contexts: prod, qa
    change-log: classpath:/db-changelog.xml
    liquibaseSchema: liquibase
    user: APP
    password: APP
    rollback-file: liquibase-rollback.sql
    test-rollback-on-update: true

---

spring:
  profiles: prod
  datasource:
    driverClassName: org.apache.derby.jdbc.ClientDriver
    url: jdbc:derby://localhost/dbo-db;create=true
    username: APP
    password: APP
    hikari:
      poolName: hikari-connection-pool
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    contexts: prod
    change-log: classpath:/db-changelog.xml
    liquibaseSchema: liquibase
    user: APP
    password: APP
    rollback-file: liquibase-rollback.sql
    test-rollback-on-update: true
