all:
  children:
    dev:
      children:
        devs:
        ci-pipeline:
          hosts:
            ci-agents:
              ansible_host: ec2-3-120-32-70.eu-central-1.compute.amazonaws.com #127.0.0.[1:5]
              ansible_port: 22
              ansible_user: ubuntu
            ci-server:
              ansible_host: ec2-3-120-32-70.eu-central-1.compute.amazonaws.com
              ansible_port: 22
              ansible_user: ubuntu
            repository-server:
              ansible_host: ec2-3-120-32-70.eu-central-1.compute.amazonaws.com
              ansible_port: 22
              ansible_user: ubuntu
            sonar-server:
              ansible_host: ec2-3-120-32-70.eu-central-1.compute.amazonaws.com
              ansible_port: 22
              ansible_user: ubuntu
              sonar_db_user_password: P@ssw0rd
    pre-prod:
      hosts:
        pre-prod-db-server:
          ansible_host: ec2-18-185-92-203.eu-central-1.compute.amazonaws.com
          ansible_port: 22
          ansible_user: ubuntu
        pre-prod-app-server:
          ansible_host: ec2-18-185-92-203.eu-central-1.compute.amazonaws.com
          ansible_port: 22
          ansible_user: ubuntu
  vars:
    ansible_python_interpreter: /usr/bin/python3
