server:
  port: 8080
  servlet:
    context-path: /dbo

---

spring:
  profiles: prod
  datasource:
    platform: derby
    driverClassName: org.apache.derby.jdbc.ClientDriver
    url: jdbc:derby://localhost/db;create=true
    username: APP
    password: APP
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: prod
    enabled: true
    change-log: classpath:/db/liquibase-changelog-test.groovy
    user: APP
    password: APP
    liquibaseSchema: liquibase
    rollback-file: liquibase-rollback.sql
    test-rollback-on-update: true

---

spring:
  profiles: it
  datasource:
    platform: derby
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:target/db;create=true
    username: APP
    password: APP
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: it
    enabled: true
    change-log: classpath:/db/liquibase-changelog-test.groovy
    rollback-file: target/liquibase-rollback-test.sql
    user: APP
    password: APP
    liquibaseSchema: liquibase
    test-rollback-on-update: true

---

spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    contexts: test
    enabled: false
