server.port: 8080

spring:
  jpa:
    hibernate:
      show-sql: no
      ddl-auto: validate

  datasource:
    platform: derby
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:build/db;create=true
    username: APP
    password: APP

    hikari:
      poolName: hikari-pool-prod
      maximumPoolSize: 10
      connectionTimeout: 60000
      idleTimeout: 60000

  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase-changelog-test.groovy #TODO move script to integrationTest/resources and solve build profiles issue
    user: APP
    password: APP
    liquibaseSchema: liquibase
    rollback-file: liquibase-rollback.sql
    test-rollback-on-update: true

